CFLAGS="-march=native -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
RUSTFLAGS="-C force-frame-pointers=yes -C target-cpu=native"

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

COMPRESSZST=(zstd -c -T0 --auto-threads=logical -)
