#!/bin/bash

# Ags logger 

# Features :
# memoory usage logging, syntax highlighting, with caching

output_logs() {
    echo -e "$file_cache"
    echo -n 'MEM USAGE : '
    echo -n $(ps -o vsz=,rss= $(pgrep ags | tail -n 1) | awk '{print $2}' | rev | cut -c 4- | rev)
    echo 'mb'
}

cache_logs() {
    file_cache=$(pygmentize -g ~/.config/ags/ags.log)
}

while true; do 
    cache_logs
    clear
    output_logs
    sleep 1
done
