$colorFocused = rgb(4E67B1)
$colorUnfocused = rgb(162A4C)

general {
    col.active_border = $colorFocused 
    col.inactive_border = $colorUnfocused
}

group {
    groupbar {
        col.active = $colorFocused 
        col.inactive = $colorUnfocused
    }
    col.border_active = $colorFocused
    col.border_inactive = $colorUnfocused
}

decoration {
    shadow {
        color = $colorUnfocused
    }
}
