#!/bin/bash

TMPPCK=$(hyprpicker -a -n)
TMPPST=$(wl-paste)
CMD=$(echo "$TMPPST")
TMP=/tmp/xcolor_$CMD.png

hyprpick() {
  $TMPPCK
}

main() {
    convert -size 120x120 xc:"$CMD" "$TMP"
    printf %s "$CMD" | wl-paste 

    notify-send -a "Color Picker" -i "$TMP" "$CMD"
}

hyprpick
main
