#!/bin/bash

CUR_SHADER=$(hyprctl getoption decoration:screen_shader | grep "str:" | awk '{print $2}')

hyprctl keyword decoration:screen_shader "" # Off with the shaders
CMD=$(hyprpicker -a -n)
hyprctl keyword decoration:screen_shader $CUR_SHADER # Put them back

TMP=/tmp/xcolor_$CMD.png

printf %s "$CMD" | wl-paste
notify-send -a "hyprpicker" "Hyprpicker:" -i "$TMP" "$CMD"
