#!/usr/bin/bash

swayidle -w

swaylock --screenshots \
    --clock \
    --indicator-idle-visible \
    --indicator-radius 80 \
    --indicator-thickness 7 \
    --ignore-empty-password \
    --ring-color 131313 \
    --ring-ver-color 131313 \
    --ring-wrong-color C2212E \
    --key-hl-color C2212E \
    --text-color ffffff \
    --text-ver-color ffffff \
    --text-wrong-color EE4F84 \
    --line-color 00000000 \
    --inside-color 00000088 \
    --inside-ver-color 00000088 \
    --inside-wrong-color 00000088 \
    --separator-color 00000000 \
    --fade-in 3 \
    --effect-blur 6x3 \
    --effect-vignette 0.5:0.5 \
    -c 0B0A10ff \
    -K
kill %%
