#!/bin/bash

# Start a wayVNC server casting a fake screen to my tablet
wayvnc &

hyprctl output destroy WAYVNC-1
hyprctl output create headless WAYVNC-1

# define workspaces
hyprctl keyword workspace 5,monitor:WAYVNC-1

wayvncctl output-set WAYVNC-1
