# Wallpaper
exec-once = app2unit -- swww-daemon

# Core components (dbus, polkit, scrn_clr_calib)
exec-once = app2unit -- wl-gammactl -c 1.1 -b 0.98 -g 0.98
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Daemons (notif, term server, IME)
exec-once = app2unit -- dunst
exec-once = app2unit -- foot --server
exec-once = app2unit -- fcitx5 -d

# Widgets & Cursor
exec-once = wal -R
exec-once = hyprctl setcursor miku-cursor-linux 16
