# ██╗░░██╗██╗░░░██╗██████╗░██████╗░██╗░░░░░░█████╗░███╗░░██╗██████╗░
# ██║░░██║╚██╗░██╔╝██╔══██╗██╔══██╗██║░░░░░██╔══██╗████╗░██║██╔══██╗
# ███████║░╚████╔╝░██████╔╝██████╔╝██║░░░░░███████║██╔██╗██║██║░░██║
# ██╔══██║░░╚██╔╝░░██╔═══╝░██╔══██╗██║░░░░░██╔══██║██║╚████║██║░░██║
# ██║░░██║░░░██║░░░██║░░░░░██║░░██║███████╗██║░░██║██║░╚███║██████╔╝
# ╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░
#
#                                                        - zerachiel016

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀ █▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄ ▄█

source=~/.config/hypr/variables.conf #variables
source=~/.config/hypr/keybinds.conf #key bindings
source=~/.config/hypr/windowrules.conf # window rules

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

monitor=,preferred,auto,auto

# █▀ █▀▀ █▀▀ ▀█▀ █ █▀█ █▄░█ █▀
# ▄█ ██▄ █▄▄ ░█░ █ █▄█ █░▀█ ▄█

general {
    gaps_in = 4
    gaps_out = 8
    float_gaps = 10
    border_size = 2

    snap {
        enabled = true
        respect_gaps = 10
    }
}

decoration {
    rounding = 10

    blur {
        size = 3
    }

    shadow {
        range = 20 
        render_power = 3
        color = 0xdd000000
    }
}

input {
    kb_layout = us, fr
    kb_options = caps:swapescape, grp:alt_shift_toggle
    touchpad {
        disable_while_typing = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

group {
    groupbar {
        render_titles = false
        height = -3
    }
}

animations {
    bezier=woosh,0.3, 0.6, 0, 1.08
    bezier=woosh2,0.3, 0.6, 0, 1.2

    animation=windows,1,6,woosh2,slide top
    animation=windowsIn,1,5,woosh,popin 20%
    animation=windowsOut,1,8,woosh2,slide

    animation=workspaces,1,8,woosh,slidevert
}

render {
    new_render_scheduling = true
}

dwindle {
    preserve_split = yes
}
