# Wallpaper
exec-once = app2unit -- awww-daemon

# Daemons
exec-once = app2unit -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = app2unit -- udiskie
exec-once = app2unit -- wl-paste --watch cliphist store
exec-once = app2unit -- dunst
exec-once = app2unit -- foot --server
