# ██╗░░██╗██╗░░░██╗██████╗░██████╗░██╗░░░░░░█████╗░███╗░░██╗██████╗░
# ██║░░██║╚██╗░██╔╝██╔══██╗██╔══██╗██║░░░░░██╔══██╗████╗░██║██╔══██╗
# ███████║░╚████╔╝░██████╔╝██████╔╝██║░░░░░███████║██╔██╗██║██║░░██║
# ██╔══██║░░╚██╔╝░░██╔═══╝░██╔══██╗██║░░░░░██╔══██║██║╚████║██║░░██║
# ██║░░██║░░░██║░░░██║░░░░░██║░░██║███████╗██║░░██║██║░╚███║██████╔╝
# ╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░
#
#                                                        - zerachiel016

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀ █▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄ ▄█

source=~/.config/hypr/env.conf #variables
source=~/.config/hypr/execs.conf #startup
source=~/.config/hypr/keybinds.conf #key bindings
source=~/.config/hypr/windowrules.conf # window rules

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

monitor=,preferred,auto,auto

# █▀ █▀▀ █▀▀ ▀█▀ █ █▀█ █▄░█ █▀
# ▄█ ██▄ █▄▄ ░█░ █ █▄█ █░▀█ ▄█

general {
    gaps_in = 5
    gaps_out = 10
    float_gaps = 10
    border_size = 2

    snap {
        enabled = true
        respect_gaps = 10
    }
}

decoration {
    screen_shader = ~/.config/hypr/shaders/enhance_colors.glsl
    rounding = 6
    dim_inactive = true
    dim_strength = 0.3

    blur {
        size = 3
    }

    shadow {
        range = 20 
        render_power = 3
        color = 0xdd000000
    }
}

input {
    kb_layout = us, fr
    kb_options = caps:swapescape, grp:alt_shift_toggle
    touchpad {
        disable_while_typing = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

group {
    groupbar {
        render_titles = false
        indicator_height = 4
        rounding = 2
    }
}

animations {
    bezier=niercurve, 0.4, 0, 0.2, 1

    animation=windows,      1, 4, niercurve, slide
    animation=windowsOut,   1, 3, niercurve, slide
    animation=fade,         1, 4, niercurve
    animation=workspaces,   1, 4.5, niercurve, slidevert
}

render {
    new_render_scheduling = true
}

dwindle {
    preserve_split = yes
}
