# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄

# Apps & Utilities
bind = SUPER, T, exec, $term_instance --title nyaa
bind = SUPER, RETURN, exec, $term_instance
bind = SUPER, E, exec, $term $fmcli
bind = SUPER SHIFT, E, exec, $fm
bind = SUPER, D, exec, $menu
bind = SUPER, N, exec, $term_nogap nvim

# Brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 1%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 1%-

bind = SUPER SHIFT, C, exec, bash $scriptsHypr/colorpicker.sh

# Media
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Screenshots
bindl =, Print, exec, bash $scriptsHypr/screenshot.sh --copy-screen
bindl = CTRL, Print, exec, bash $scriptsHypr/screenshot.sh --copy-region
bindl = SHIFT, Print, exec, bash $scriptsHypr/screenshot.sh
bindl = ALT, Print, exec, bash $scriptsHypr/screenshot.sh --keep-shader

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▄▀█ █▀▀ █▄░█ ▀█▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █░▀░█ █▀█ █░▀█ █▀█ █▄█ █░▀░█ ██▄ █░▀█ ░█░
bind = SUPER, Q, killactive,
bind = SUPER SHIFT, A, exit ,
bind = SUPER, F, togglefloating, 
bind = SUPER ALT, Space, fullscreenstate, 
bind = SUPER, Space, fullscreen,
bind = SUPER, M, fullscreen, 1

# Dwindle
bind = SUPER, P, pin,
bind = SUPER, P, resizeactive,exact 33% 32%
bind = SUPER, S, togglesplit,
bind = SUPER SHIFT, F, workspaceopt, allfloat
bind = SUPER, c, centerwindow,
binde = ALT, Tab, exec, hyprctl dispatch cyclenext && hyprctl dispatch bringactivetotop

# Special Workspace
bind = SUPER, 0, togglespecialworkspace
bind = SUPER, x, movetoworkspace, special

# Focus
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

# Move
bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, j, movewindow, d
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, l, movewindow, r

# Resize
binde = SUPER CTRL, h, resizeactive, -20 0
binde = SUPER CTRL, j, resizeactive, 0 20
binde = SUPER CTRL, k, resizeactive, 0 -20
binde = SUPER CTRL, l, resizeactive, 20 0

# Groups
bind = SUPER, G, togglegroup
bind = SUPER SHIFT, G, moveoutofgroup 
bind = SUPER, tab, changegroupactive, f
bind = SUPER SHIFT, tab, changegroupactive, b

# Workspace
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6

# Move to workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6

# Move to workspace silently
bind = SUPER CTRL, 1, movetoworkspacesilent, 1
bind = SUPER CTRL, 2, movetoworkspacesilent, 2
bind = SUPER CTRL, 3, movetoworkspacesilent, 3
bind = SUPER CTRL, 4, movetoworkspacesilent, 4
bind = SUPER CTRL, 5, movetoworkspacesilent, 5
bind = SUPER CTRL, 6, movetoworkspacesilent, 6

# Group
bind = SUPER ALT, h, movewindoworgroup, l
bind = SUPER ALT, j, movewindoworgroup, d
bind = SUPER ALT, k, movewindoworgroup, u
bind = SUPER ALT, l, movewindoworgroup, r

# Mouse binding
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = SUPER, mouse_down, workspace, e-1
bind = SUPER, mouse_up, workspace, e+1
