windowrule {
  name = floating_terms
  float = on
  size = 850 480
  match:title = (nyaa)
}


# Pinned
windowrule {
  name = 
  no_blur = on
  no_dim = on
  no_shadow = on
  opacity = 0.75
  match:pin = 1
}
